Primera subida
MacielFede/Entrenamos.uy pull request #1
Opened 2023-08-13 02:08 UTC by MacielFede

I did this PR to start the project and not have it blank.
The swing code existing is something that I saw in a yt tutorial, maybe we need to change some stuff.

2023-08-14 01:10 UTC, tongawz requested changes
Remove /.idea/dictionaries and his content

2023-08-14 01:12 UTC, tongawz commented on .idea/dictionaries/macilon.xml
Delete

2023-08-16 03:00 UTC, tongawz approved these changes

2023-08-16 03:01 UTC, fvigliarolo approved these changes
dudas?

2023-08-16 03:10 UTC, michaelramos95 approved these changes
Leave a comment

2023-08-16 03:10 UTC, merged