Factory, Interfaces, Controllers and Services
MacielFede/Entrenamos.uy pull request #5
Opened 2023-08-18 19:04 UTC by michaelramos95

En un principio los set retornados, los representé como List, si es necesario cambiar esto me comentan.

2023-08-18 19:09 UTC, tongawz requested changes
I suggest the use of maps, then they will help us in the graphical interface for ddls and etc. because its pairs, key-value

2023-08-19 15:53 UTC, fvigliarolo submitted a review, later dismissed

2023-08-19 22:58 UTC, axel-lois commented
> I suggest the use of maps, then they will help us in the graphical interface for ddls and etc. because its pairs, key-value

Agree with this.

2023-08-20 13:17 UTC, axel-lois submitted a review, later dismissed

2023-08-20 13:42 UTC, axel-lois approved these changes

2023-08-20 13:42 UTC, tongawz approved these changes

2023-08-20 13:42 UTC, merged